require("vim._core.ui2").enable({})

-- core
require("christphralden.core.pack")
require("christphralden.core.commands")

-- plugins
require("christphralden.plugins.cmp")
require("christphralden.plugins.lsp")
require("christphralden.plugins.autopairs")
require("christphralden.plugins.autotag")
require("christphralden.plugins.telescope")
require("christphralden.plugins.treesitter")
-- require("christphralden.plugins.colors.rose-pine")
require("christphralden.plugins.colors.lackluster")
require("christphralden.plugins.grapple")
require("christphralden.plugins.conform")
require("christphralden.plugins.gitsigns")
require("christphralden.plugins.notify")
require("christphralden.plugins.noice")
require("christphralden.plugins.zen")
require("christphralden.plugins.goto")
require("christphralden.plugins.treesj")
require("christphralden.plugins.scratchpad")
require("christphralden.plugins.alpha")

require("christphralden.core.options")
require("christphralden.core.keymaps")
require("christphralden.core.autocommands")
require("christphralden.core.statusline")
